### ISSUE TITLE
List will never load after restoring from low memory condition (process death)

### ISSUE THREAD

**Issue by Zhuinden** [Benyuss/RefinedCleanArchitecture-Android#1]
![image](https://user-images.githubusercontent.com/11718392/51354994-dff09700-1ab5-11e9-9063-87c67715df88.png)

**Comment by Zhuinden** [comment]
```
01-18 00:14:21.628 3743-3743/com.borosbence.rfca E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
    kotlin.KotlinNullPointerException
        at com.borosbence.rfca.presentation.users.presenter.UserPresenterImpl$setSearchListeners$1.onQueryTextChange(UserPresenterImpl.kt:119)
        at android.widget.SearchView.onTextChanged(SearchView.java:1209)
        at android.widget.SearchView.-wrap9(SearchView.java)
        at android.widget.SearchView$9.onTextChanged(SearchView.java:1682)
        at android.widget.TextView.sendOnTextChanged(TextView.java:7991)
        at android.widget.TextView.handleTextChanged(TextView.java:8053)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10157)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:223)
        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
        at android.widget.TextView.doKeyDown(TextView.java:6098)
        at android.widget.TextView.onKeyDown(TextView.java:5911)
        at android.widget.AutoCompleteTextView.onKeyDown(AutoCompleteTextView.java:720)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2640)
        at android.view.View.dispatchKeyEvent(View.java:9234)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:130)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
    	at android.view.ViewRootI
```
